### ISSUE TITLE
[TRG 4.06] Move "Notice for docker images" to separate file

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/managed-simple-data-exchanger-backend#104]
Please move the Notice for docker images into a separate file. Although the current [TRG](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) version does not require it explicitly, you are running into a problem we discussed in one of the Office hours end of last year:
If you got a long `README.md` file with the notice at the end (where it should be) Dockerhub is cutting the Readme which will result in a published image without notice. Unfortunately the notice is legally required.

hint: the docker workflow has to be adjusted to include the `notice.md`: https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06

**Comment by adityagajbhiye9** [comment]
@hzierer  I have created the Docker notice and raised the PR #101

**Comment by hzierer** [comment]
fixed with PR #101
