### ISSUE TITLE
`2.3.6` Image won't Start because `edc_request_template` Files are missing

### ISSUE THREAD

**Issue by efiege** [eclipse-tractusx/managed-simple-data-exchanger-backend#147]
### Current Behavior
SDE-Backend won't start as `edc_request_template` Files are missing in the repository.

They are also currently not included on the main branch, as one can see [here](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/tree/main/modules/sde-core/src/main/resources/edc_request_template%0A).

### Steps To Reproduce
- Start the `tractusx/managed-simple-data-exchanger-backend:2.3.6` Image

**Comment by sachinargade123** [comment]
@efiege, Thanks for reporting issue. It will fix in next release. The next release will be available within week.

**Comment by efiege** [comment]
@sachinargade123 Thanks for the quick reply! Could this also be backported to the `2.3.6` version, which is mandatory for the Tractus-X Release 24.03?

We are happy to help, if we can do anything!

**Comment by SebastianOpriel** [comment]
@sachinargade123 any update on that topic? SDE is [prescribed in Catena-X 24/03 as v2.3.6](https://eclipse-tractusx.github.io/CHANGELOG). But SDE is simply not working in v2.3.6.

**Comment by sachinargade123** [comment]
Yes, We will provide fix for this release version.

**Comment by SebastianOpriel** [comment]
Awesome to here. Any estimation or gut-feeling when it will be available?

**Comment by adityagajbhiye9** [comment]
@efiege We are working on it . I Will provide update after release.

**Comment by adityagajbhiye9** [comment]
@SebastianOpriel @efiege release has been done  appversion v2.3.7

**Comment by adityagajbhiye9** [comment]
closing the issue .
