### ISSUE TITLE
docs: appropriate `README.md`

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger-backend#44]
Please see [TRG1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) and other TRGs in the list.

The readme is missing the following sections:

- How to configure the application
- Reference to an INSTALL.md
- Reference to the leading product repository and backend repository according to the [TRG2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4#description)
- Notice for Docker image or reference to the notice based on [TRG4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06). You can find a good example for the notice section [here](https://github.com/eclipse-tractusx/item-relationship-service/blob/main/README.md?plain=1#L85).

**Comment by adityagajbhiye9** [comment]
Read me Updated according to TRGs.

**Comment by adityagajbhiye9** [comment]
we have updated Read me .
