### ISSUE TITLE
docs: rename InstallationGuide.md to INSTALL.md and fix content

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger-backend#45]
Please rename `InstallationGuide.md` to `INSTALL.md` and update the content of the file as it looks out of date and steps are not relevant anymore. Also please reference the INSTALL.md file in the README.md as well.

**Comment by adityagajbhiye9** [comment]
Renamed the Installation guide and we  have fixed content in it.
