### ISSUE TITLE
Need to reset main branch to a specific commit on request

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger-backend#67]
Based on the request of @adityagajbhiye9 the following has to be done:

- Delete release 2.3.0
- Reset main branch HEAD to commit c6fa04a58dfa9b6f75eeb9b2ff1510f00c5f54a1

@adityagajbhiye9 please confirm.

**Comment by adityagajbhiye9** [comment]
verified and confirm.
Thanks

**Comment by almadigabor** [comment]
Done, please check. Steps I did:

1. Clone main branch to local machine
2. Hard reset to desired commit `git reset --hard c6fa04a`
3. Delete remote tag main `git push --delete origin refs/tags/main`
4. Delete local tag main `git tag -d main`
5. Force push local branch to origin main `git push -f origin main`

Final output: 

```
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend.git
 + e2691d96...c6fa04a5 main -> main (forced update)
```

**Comment by almadigabor** [comment]
Let me know if the issue can be closed.

**Comment by adityagajbhiye9** [comment]
Please close the issue.
