### ISSUE TITLE
Dockerfile: UID 1001 and "useradd -r ..." are mutally exclusive

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/managed-simple-data-exchanger-backend#69]
Hi @adityagajbhiye9,

your [Dockerfile ](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/c6fa04a58dfa9b6f75eeb9b2ff1510f00c5f54a1/build/Dockerfile#L37-L42) is working, but is not best practice.

Background: "useradd -r ..." creates a so called system account. which get by default a uid between 100-999

Please use either a uid from the range above or call useradd without "r" like this:
`RUN useradd -m -d /home/sdeuser -s /bin/bash -u $USER_UID -U $USERNAME`

**Comment by adityagajbhiye9** [comment]
@hzierer Changed the uid to 101.

**Comment by sachinargade123** [comment]
@hzierer We have provided fix with this commit https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/pull/68/commits/2b6317010d48f7a71b155e71845c25813cad4c37
