### ISSUE TITLE
Example CSV for assembly-part-relationship does not match the documentation and json definition

### ISSUE THREAD

**Issue by a-trzewik** [eclipse-tractusx/managed-simple-data-exchanger-backend#70]
The CSV Example for assembly-part-relationship submodule

https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/main/modules/sde-submodules/assembly-part-relationship/src/main/resources/assemblyPartRelationship.csv

Does not match the documentation

https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/main/modules/sde-submodules/assembly-part-relationship/assembly-part-relationship.md

The csv example is even linked from the documentation

And json schema

modules/sde-submodules/assembly-part-relationship/src/main/resources/assembly-part-relationship.json

**Comment by adityagajbhiye9** [comment]
@ChetanT-System  @sachinargade123 Please check.
