### ISSUE TITLE
[TRG 7.01] outdated notice.md file

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/managed-simple-data-exchanger-backend#71]
Hi @sachinargade123, @adityagajbhiye9,

can you please update your notice.md file. As it still [points to](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/blob/c6fa04a58dfa9b6f75eeb9b2ff1510f00c5f54a1/NOTICE.md?plain=1#L32) to DFT.

**Comment by adityagajbhiye9** [comment]
Updated the latest git repo.
